#!/usr/bin/env node

const {
  TableOfContentsBuilder
} = require('../utils/toc-builder');

const opts = {
  pattern: 'content/docs/**/*.md',
  out: 'content/docs-toc.js'
}


const tocb = new TableOfContentsBuilder(opts);

(async () => {
  await tocb.handle();

})();


