{
 "title": "starter dashboard",
 "time": { "from": "now/w", "to": "now/w" },
 "refresh": "30s",
 "panels": [
  {
   "title": "SypexGeo Countries",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((sxgeo_country_en, amount))\nFROM\n(\n    SELECT\n        sxgeo_country_en,\n        uniq(uid) AS amount\n    FROM $table\n    WHERE $timeFilter and name = 'session'\n    GROUP BY sxgeo_country_en\n    ORDER BY amount desc\n    LIMIT 5\n)",
     "rawQuery": "SELECT     1,     groupArray((sxgeo_country_en, amount)) FROM (     SELECT         sxgeo_country_en,         uniq(uid) AS amount     FROM stats.events     WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) and name = 'session'     GROUP BY sxgeo_country_en     ORDER BY amount desc     LIMIT 5 )",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Sites stat",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    date,\n    domain(page_url) as site_domain,\n    uniq(uid) as users,\n    countIf(name = 'session') as sessions,\n    countIf(name = 'page') as pages,\n    count() as events\nFROM $table\nWHERE $timeFilter\nGROUP BY date, site_domain\nORDER BY date, site_domain DESC",
     "rawQuery": "SELECT     date,     domain(page_url) as site_domain,     uniq(uid) as users,     countIf(name = 'session') as sessions,     countIf(name = 'page') as pages,     count() as events FROM stats.events WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) GROUP BY date, site_domain ORDER BY date, site_domain DESC",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((sess_type,  Events))\nFROM\n(\n    SELECT\n        sess_type,\n        count() AS Events\n    FROM $table\n    WHERE $timeFilter AND name = 'session'\n    GROUP BY sess_type\n    ORDER BY Events desc\n    LIMIT 20\n)",
     "rawQuery": "SELECT     1,     groupArray((sess_type,  Events)) FROM (     SELECT         sess_type,         count() AS Events     FROM stats.events     WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) AND name = 'session'     GROUP BY sess_type     ORDER BY Events desc     LIMIT 20 )",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "    SELECT\n        $timeSeries t,\n        uniq(uid) as amount\n    FROM $table\n    WHERE\n        $timeFilter and name = 'session' and uaparser_is_bot != 1\n    GROUP BY t\n    ORDER BY t",
     "rawQuery": "    SELECT         (intDiv(toUInt32(dateTime), 1800) * 1800) * 1000 t,         uniq(uid) as amount     FROM stats.events     WHERE         date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) and name = 'session' and uaparser_is_bot != 1     GROUP BY t     ORDER BY t",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "    SELECT\n        $timeSeries t,\n        count() as amount\n    FROM $table\n    WHERE\n        $timeFilter and name = 'page'\n    GROUP BY t\n    ORDER BY t",
     "rawQuery": "    SELECT         (intDiv(toUInt32(dateTime), 1800) * 1800) * 1000 t,         count() as amount     FROM stats.events     WHERE         date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) and name = 'page'     GROUP BY t     ORDER BY t",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "New users/returning",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((userType,  Events))\nFROM\n(\n    SELECT\n        if(sess_num = 1,  'New',  'Returning') as userType,\n        count() AS Events\n    FROM $table\n    WHERE\n        $timeFilter\n        AND name = 'session'\n    GROUP BY userType\n    ORDER BY Events desc\n    LIMIT 10\n)",
     "rawQuery": "SELECT     1,     groupArray((userType,  Events)) FROM (     SELECT         if(sess_num = 1,  'New',  'Returning') as userType,         count() AS Events     FROM stats.events     WHERE         date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599)         AND name = 'session'     GROUP BY userType     ORDER BY Events desc     LIMIT 10 )",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "SypexGeo city RU",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((sxgeo_city_en, amount))\nFROM\n(\n    SELECT\n        sxgeo_city_en,\n        uniq(uid) AS amount\n    FROM $table\n    WHERE $timeFilter and sxgeo_country_iso = 'RU' and name = 'session'\n    GROUP BY sxgeo_city_en\n    ORDER BY amount desc\n    LIMIT 5\n)",
     "rawQuery": "SELECT     1,     groupArray((sxgeo_city_en, amount)) FROM (     SELECT         sxgeo_city_en,         uniq(uid) AS amount     FROM stats.events     WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) and sxgeo_country_iso = 'RU' and name = 'session'     GROUP BY sxgeo_city_en     ORDER BY amount desc     LIMIT 5 )",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    name,\n    count() c)\nFROM $table",
     "rawQuery": "SELECT t, groupArray((name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(dateTime), 900) * 900) * 1000 as t, name, count() c FROM stats.activity WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) GROUP BY t, name  ORDER BY t, name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "activity"
    },
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    name,\n    count() c)\nFROM $table",
     "rawQuery": "SELECT t, groupArray((name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(dateTime), 900) * 900) * 1000 as t, name, count() c FROM stats.events WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) GROUP BY t, name  ORDER BY t, name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Events / Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    name,\n    count()/uniq(uid) c)\nFROM $table",
     "rawQuery": "SELECT t, groupArray((name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(dateTime), 1800) * 1800) * 1000 as t, name, count() / uniq(uid) c FROM stats.activity WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) GROUP BY t, name  ORDER BY t, name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "activity"
    },
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    name,\n    count()/uniq(uid) c)\nFROM $table",
     "rawQuery": "SELECT t, groupArray((name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(dateTime), 1800) * 1800) * 1000 as t, name, count() / uniq(uid) c FROM stats.events WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) GROUP BY t, name  ORDER BY t, name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1, /* fake timestamp value */\n    transform(uaparser_is_mob*3 + uaparser_is_pc*8, [8, 3], ['PC', 'Mobile'], 'Strange') as grp,\n    uniq(uid) AS amount\nFROM $table\nWHERE $timeFilter and name = 'session' and uaparser_browser_family != ''\nGROUP BY grp\nORDER BY amount desc\nLIMIT 5\n\n",
     "rawQuery": "SELECT     1, /* fake timestamp value */     transform(uaparser_is_mob*3 + uaparser_is_pc*8, [8, 3], ['PC', 'Mobile'], 'Strange') as grp,     uniq(uid) AS amount FROM stats.events WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) and name = 'session' and uaparser_browser_family != '' GROUP BY grp ORDER BY amount desc LIMIT 5  ",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "MaxMind Countries",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 16 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((mmgeo_country_en, amount))\nFROM\n(\n    SELECT\n        mmgeo_country_en,\n        uniq(uid) AS amount\n    FROM $table\n    WHERE $timeFilter and name = 'session'\n    GROUP BY mmgeo_country_en\n    ORDER BY amount desc\n    LIMIT 5\n)",
     "rawQuery": "SELECT     1,     groupArray((mmgeo_country_en, amount)) FROM (     SELECT         mmgeo_country_en,         uniq(uid) AS amount     FROM stats.events     WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) and name = 'session'     GROUP BY mmgeo_country_en     ORDER BY amount desc     LIMIT 5 )",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "MaxMind city RU",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 16 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((mmgeo_city_en, amount))\nFROM\n(\n    SELECT\n        mmgeo_city_en,\n        uniq(uid) AS amount\n    FROM $table\n    WHERE $timeFilter and mmgeo_country_iso = 'RU' and name = 'session'\n    GROUP BY mmgeo_city_en\n    ORDER BY amount desc\n    LIMIT 5\n)",
     "rawQuery": "SELECT     1,     groupArray((mmgeo_city_en, amount)) FROM (     SELECT         mmgeo_city_en,         uniq(uid) AS amount     FROM stats.events     WHERE date BETWEEN toDate(1536526800) AND toDate(1537131599) AND dateTime BETWEEN toDateTime(1536526800) AND toDateTime(1537131599) and mmgeo_country_iso = 'RU' and name = 'session'     GROUP BY mmgeo_city_en     ORDER BY amount desc     LIMIT 5 )",
     "round": "0s",
     "table": "events"
    }
   ]
  }
 ]
}